### ISSUE TITLE
v1.4.1 stopped working with original Molekule Air

### ISSUE THREAD

**Issue by brianysf** [csirikak/homebridge-molekule#11]
Not sure if you're still supporting the original Molekule Air. I tried removing the cached accessory but it's still failing.

07/11/2023, 02:16:03] [homebridge-molekule] Adding new accessory: Molekule Air
/usr/local/lib/node_modules/homebridge-molekule/src/platformAccessory.ts:94
    if (this.accessory.context.device.capabilities.AutoFunctionality) {
                                                   ^
TypeError: Cannot read properties of undefined (reading 'AutoFunctionality')
    at new MolekulePlatformAccessory (/usr/local/lib/node_modules/homebridge-molekule/src/platformAccessory.ts:94:52)
    at /usr/local/lib/node_modules/homebridge-molekule/src/platform.ts:172:9
    at Array.forEach (<anonymous>)
    at MolekuleHomebridgePlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-molekule/src/platform.ts:108:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[07/11/2023, 02:16:03] [homebridge-molekule] Child bridge process ended

**Comment by csirikak** [comment]
Can you post a full log with the debug mode enabled?

**Comment by dannys42** [comment]
I believe I have the same issue.  I also have the original Molekule Air.  What I'm seeing is this:

```
[1/1/2024, 10:48:35 PM] [homebridge-molekule] ✓ Valid Login Credentials
[1/1/2024, 10:48:35 PM] [homebridge-molekule] Adding new accessory: Master Bedroom
[1/1/2024, 10:48:35 PM] TypeError: Cannot read properties of undefined (reading 'AutoFunctionality')
    at new MolekulePlatformAccessory (/homebridge/node_modules/homebridge-molekule/src/platformAccessory.ts:94:52)
    at /homebridge/node_modules/homebridge-molekule/src/platform.ts:172:9
    at Array.forEach (<anonymous>)
    at MolekuleHomebridgePlatform.discoverDevices (/homebridge/node_modules/homebridge-molekule/src/platform.ts:108:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/1/2024, 10:48:35 PM] Got SIGTERM, shutting down Homebridge...
[1/1/2024, 10:48:45 PM] [homebridge-molekule] Initializing Molekule platform...
```

To answer your questions:
* How do we enable debug mode?
* Don't know about the fan speed number.  Beyond the 3 modes (below), I don't see a way to control the fan.
* The modes I see in the app are: Silent, Auto, Boost
* There is no air quality sensor that I know of.

**Comment by csirikak** [comment]
> * How do we enable debug mode?

To run homebridge in debug mode you can try `homebridge -D` if you're using the command line, otherwise you can also do it in the UI under startup options.
![image](https://github.com/csirikak/homebridge-molekule/assets/32028457/7a1cea5c-f5e6-4307-b450-7a274227f84d)

**Comment by dmavromatis** [comment]
Same thing is happening to me with an original Molekule Air: Cannot read properties of undefined (reading 'AutoFunctionality') -- let me know what you need.

**Comment by csirikak** [comment]
Please try version `v1.4.2-alpha`

**Comment by dmavromatis** [comment]
That works -- Thanks!!
