### ISSUE TITLE
Plugin failing with 1.4.0

### ISSUE THREAD

**Issue by heccoder** [csirikak/homebridge-molekule#9]
The most recent update (1.4.0) broke something in my configuration, I'm getting the following in the homebridge logs:
```

[9/8/2023, 11:58:11 PM] [homebridge-molekule] Launched child bridge with PID 6570
[9/8/2023, 11:58:11 PM] Registering platform 'homebridge-molekule.Molekule'
[9/8/2023, 11:58:11 PM] [homebridge-molekule] Loaded homebridge-molekule v1.4.0 child bridge successfully
[9/8/2023, 11:58:11 PM] Loaded 0 cached accessories from cachedAccessories.XXXXXXXXXXXX.
[9/8/2023, 11:58:11 PM] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-molekule) is running on port 44641.
[9/8/2023, 11:58:13 PM] [homebridge-molekule] ✓ Valid Login Credentials
[9/8/2023, 11:58:13 PM] [homebridge-molekule] Adding new accessory: Molekule Downstairs

/usr/lib/node_modules/homebridge-molekule/src/platformAccessory.ts:22
  private maxSpeed = this.accessory.context.device.capabilities.MaxFanSpeed ?? 6 //defaults to max speed of 6 if device not in JSON
                                                                ^
TypeError: Cannot read properties of undefined (reading 'MaxFanSpeed')
    at new MolekulePlatformAccessory (/usr/lib/node_modules/homebridge-molekule/src/platformAccessory.ts:22:65)
    at /usr/lib/node_modules/homebridge-molekule/src/platform.ts:140:9
    at Array.forEach (<anonymous>)
    at MolekuleHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-molekule/src/platform.ts:95:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/8/2023, 11:58:13 PM] [homebridge-molekule] Child bridge process ended
[9/8/2023, 11:58:13 PM] [homebridge-molekule] Process Ended. Code: 1, Signal: null
[9/8/2023, 11:58:20 PM] [homebridge-molekule] Restarting Process...
```

I tried disabling the child bridge for the plugin and cleared cached accessories. Any ideas? 
Thank you!

**Comment by csirikak** [comment]
Can you do the same thing again with homebridge debug mode?

**Comment by sonoseco** [comment]
Here's in debug mode, removed some possible identifiable info:

```
[homebridge-molekule] HTTP GET STATUS: 200
[9/9/2023, 2:28:29 AM] [homebridge-molekule] found device from API: {"serialNumber":"XXXXREMOVEDXXXX","name":"Molekule Downstairs","subProduct":{"id":3,"name":"Molekule Air","product":{"id":3,"name":"MH","description":"Molekule Air","serialNumberPrefix":"MH","health":["sn","fw","dc"]},"createdBy":"admin-app@molekule.com","createdAt":"2020-03-18T12:11:58.462Z","updatedBy":"admin-app@molekule.com","updatedAt":"2020-03-18T12:11:58.462Z","serialNumberPrefix":"MH1"},"firmwareVersion":"FW:8.31.2","model":"Molekule Air","firstConnectedUser":"XXXXXXXX-a402-4418-8fcf-XXXXXXXXXX","firstConnectionDate":"2023-05-02T16:31:50.375Z","macAddress":"XX:XX:XX:XX:XX:XX","pecoFilter":"0","fanspeed":"2","online":"true","preFilter":"0","silent":"","burst":"N/A"}
[9/9/2023, 2:28:29 AM] [homebridge-molekule] Adding new accessory: Molekule Downstairs
[9/9/2023, 2:28:29 AM] TypeError: Cannot read properties of undefined (reading 'MaxFanSpeed')
    at new MolekulePlatformAccessory (/usr/lib/node_modules/homebridge-molekule/src/platformAccessory.ts:22:65)
    at /usr/lib/node_modules/homebridge-molekule/src/platform.ts:140:9
    at Array.forEach (<anonymous>)
    at MolekuleHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-molekule/src/platform.ts:95:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by sonoseco** [comment]
I tried downgrading to a previous version of the plugin but it's also failing. Maybe a new device firmware version causing this?
For now I disabled the plugin since it keeps crashing homebridge.

**Comment by csirikak** [comment]
I see, the `Molekule Air` doesn't exist as a device class in the `devices.json`
Could you tell me what is the max fan speed i.e. 5 or 6
Does it have auto mode?
Does it report air quality?

**Comment by sonoseco** [comment]
I don't see a fan speed for this model, only silent, auto and boost modes. It doesn't report air quality.

I just installed version 1.2.1 and it's working good again!

**Comment by csirikak** [comment]
> I don't see a fan speed for this model, only silent, auto and boost modes. It doesn't report air quality.
> 
> 
> 
> I just installed version 1.2.1 and it's working good again!

Would you be able to take screenshots from the Molekule app and post them here? I'd like to make sure your device is added properly in the latest version. Version 1.2.1 is hardcoded for the Air Mini Basic and only includes on/off and set fan speed capability.

**Comment by QandnotU** [comment]
@csirikak I have a Air Mini Basic too, I can pull it out of the closet and get it setup and report back my findings and provide what you need. Let me know.

**Comment by csirikak** [comment]
I'm looking for info on the Molekule Air actually.

**Comment by aharderharmony** [comment]
Hello, I have the same problem, had to downgrade to 1.2.1 to get it working. Screen captures of which screens in the app would help most?

**Comment by csirikak** [comment]
Please try the latest version: v1.4.2.

**Comment by aharderharmony** [comment]
Updated to v1.4.2 but it the Molekule is not responding in HomeKit.
Below are logs after the update. I tried clearing the cached accessory.
What’s the best way to check the model name in API?

The Molekule Air has 3 fan speeds: silent, auto, and boost. Molekule support told me that there is no Air Quality sensor and auto is a constant speed.

[17/04/2024, 01:01:58] [homebridge-molekule] Launched child bridge with PID 61608
[17/04/2024, 01:01:58] Registering platform 'homebridge-molekule.Molekule'
[17/04/2024, 01:01:58] [homebridge-molekule] Loaded homebridge-molekule v1.4.2 child bridge successfully
[17/04/2024, 01:01:58] Loaded 1 cached accessories from cachedAccessories.0E798BFC4980.
[17/04/2024, 01:01:58] [homebridge-molekule] Loading accessory from cache: Molekule_1089
[17/04/2024, 01:01:59] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-molekule) is running on port 33750.
[17/04/2024, 01:02:00] [homebridge-molekule] ✓ Valid Login Credentials
[17/04/2024, 01:02:00] [homebridge-molekule] Restoring existing accessory from cache: Molekule_1089
[17/04/2024, 01:02:00] [homebridge-molekule] This plugin generated a warning from the characteristic 'Filter Change Indication': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[17/04/2024, 01:02:00] [homebridge-molekule] This plugin generated a warning from the characteristic 'Filter Life Level': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[17/04/2024, 01:02:08] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:05] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:08] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:16] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:17] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:19] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:20] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:26] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:27] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:57] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:03:58] [homebridge-molekule] Molekule_1089 sent offline status to homekit
[17/04/2024, 01:04:02] [homebridge-molekule] Molekule_1089 set speed ->  {"fanSpeed":2}
[17/04/2024, 01:04:02] [homebridge-molekule] Molekule_1089 set speed ->  {"fanSpeed":4}
[17/04/2024, 01:04:15] [homebridge-molekule] Molekule_1089 sent offline status to homekit

**Comment by csirikak** [comment]
Please try running homebridge in debug mode and then post the results under `found device from API:`
Debug mode can be activated in the settings section of the UI

**Comment by aharderharmony** [comment]
Here it is, thanks. I obfuscated a few fields.
[17/04/2024, 22:53:39] [homebridge-molekule] found device from API: {"serialNumber":"XXXX-XXXXXXXXX-XXXXXX","name":"Molekule_1089","subProduct":{"id":3,"name":"Molekule Air","product":{"id":3,"name":"MH","description":"Molekule Air","serialNumberPrefix":"MH","health":["sn","fw","dc"]},"createdBy":"admin-app@molekule.com","createdAt":"2020-03-18T12:11:58.462Z","updatedBy":"admin-app@molekule.com","updatedAt":"2020-03-18T12:11:58.462Z","serialNumberPrefix":"MH1"},"firmwareVersion":"FW:8.31.2","model":"Molekule Air","firstConnectedUser":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","firstConnectionDate":"2020-10-30T03:46:18.305Z","macAddress":"E0:4F:43:6C:XX:XX","pecoFilter":"29","fanspeed":"2","online":"true","preFilter":"96","silent":"","burst":"N/A"}

**Comment by aharderharmony** [comment]
v1.4.3 is working for my original Molekule Air. Thanks! I found that Silent mode is displayed as 17% fan speed in HomeKit, Auto is 33%, and Boost is 50%. Created scenes that match these modes and everything works!
